spring:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
      url: jdbc:mysql://localhost:3306/SPJ?serverTimezone=Asia/Seoul
      username: root
      password: as2646
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 9091

naver:
  papago: "https://openapi.naver.com/v1/papago/n2mt"
  id : "0QJhbYw2IhHIs78ihpxV"
  secret : "LSz5CRvuF4"

kakao:
  karlo: "https://api.kakaobrain.com/v1/inference/karlo/t2i"
  id : "bb67167c460f9277d6a14292f196b274"