spring:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
      url: jdbc:mysql://localhost:3306/SPJ?serverTimezone=Asia/Seoul
      username: root
      password: as2646
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: 1234
